name: PandoraUserInfo
version: 1.0-SNAPSHOT
main: me.nanigans.pandorauserinfo.PandoraUserInfo
authors: [ProNanigans]
description: User information for pandora pvp
website: www.dustie.xyz
depends: [LiteBans, Vault, Factions]
commands:
  userinfo:
    description: "Shows information on a user"
    usage: /userinfo <name>
    aliases: [whois, infouser, ui]